// src/features/user/userSlice.js
import { createSlice } from '@reduxjs/toolkit';

// Initial state for the user slice of Redux store
const initialState = {
  user: null,      // Stores the logged-in user details (e.g., id, name)
  token: null,     // JWT or auth token for authenticated requests
  loading: false,  // Boolean to track if an async login operation is in progress
  error: null      // Stores error messages from failed login attempts
};

// Create a Redux slice named 'user' using Redux Toolkit's createSlice
const userSlice = createSlice({
  name: 'user',           // Name of the slice; will be used as the key in the store
  initialState,           // Initial state object defined above
  reducers: {             // Reducers to handle state changes based on actions
    // Called when a login process starts (e.g., when user submits login form)
    loginStart: (state) => {
      state.loading = true;   // Set loading to true while waiting for server response
      state.error = null;     // Reset any previous error message
    },

    // Called when login succeeds and user data + token are received
    loginSuccess: (state, action) => {
      state.loading = false;          // Stop loading indicator
      state.user = action.payload.user;   // Save user details from payload (e.g., { id, name })
      state.token = action.payload.token; // Save JWT token from payload for authenticated API calls
    },

    // Called when login fails due to wrong credentials or server error
    loginFailure: (state, action) => {
      state.loading = false;         // Stop loading indicator
      state.error = action.payload; // Store the error message from payload for showing feedback to user
    },

    // Called when user logs out
    logout: (state) => {
      state.user = null;     // Clear user info
      state.token = null;    // Clear authentication token
      state.error = null;    // Clear any error messages
      state.loading = false; // Reset loading flag
    }
  }
});

// Export the action creators generated by createSlice
export const { loginStart, loginSuccess, loginFailure, logout } = userSlice.actions;

// Export the reducer to be used in the Redux store
export default userSlice.reducer;
